name: Django Tests

on:
  push:
    branches: [ main, unit_tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

 
        -c timezone=UTC
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Enable hstore in `test_db` and `template1`
        run: |
          psql -h localhost -U test_user -d test_db -c "CREATE EXTENSION IF NOT EXISTS hstore;"
          psql -h localhost -U test_user -d template1 -c "CREATE EXTENSION IF NOT EXISTS hstore;"
        env:
          PGPASSWORD: test_pass

      - name: Run migrations
        run: python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: modelrepository.settings
          DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db

      - name: Run tests
        run: python manage.py test --keepdb
        env:
          DJANGO_SETTINGS_MODULE: modelrepository.settings
          DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
